### PR TITLE
Solr 5

### PR DESCRIPTION
**Pull request by prateek05**
@s-u Solr 5

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
I am merging this without much review, because it doesn't touch core RCloud except for the scripts. Will test on rcloud-5 now.

**Comment by gordonwoodhull** [comment]
Thanks @prateek05!

**Comment by prateek05** [comment]
Might have to reindex after this

**Comment by gordonwoodhull** [comment]
rebased and merged, now re-indexing rcloud-5.

Thanks!

**Pull request closed without merging**
