### PR TITLE
first stab at a locator()

### PR DESCRIPTION
**Pull request by gordonwoodhull**
for #1143

Hey @s-u, here are most of the javascript bits for a locator. It takes a device id and page explicitly because I don't remember how to get the current device. It pushes the pixel coordinates to an array and then sends the array when ESC is pressed.

However, something is wrong with the continuation (or something), because I don't see the value returned, whether I pass it first or second to `k()` - the usual RCloud integration shenanigans, I'm sure.

Obviously I didn't worry about how to integrate it or translate coordinates or any of that good stuff, because I figure you know all that. I've actually been testing it in the debugger, watching the image created to get the device id, then running `rcloud.locator` with the device id. 

Theoretically there would be no problem running this on any image in the notebook, not just the current one...

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
LMK what other interface you want on it. I actually think the blue keyboard-focus highlight works pretty well. Oh, I'll add the crosshair cursor right now.

**Comment by gordonwoodhull** [comment]
Alright, there are intricacies about getting the right coordinates:

http://stackoverflow.com/questions/2159044/getting-the-x-y-coordinates-of-a-mouse-click-on-an-image-with-jquery

I think I chose the best answer there (instead of the most popular one). Of course, I'm just returning coordinates relative to the image, not the plot.

Also, crosshair! For the duration of the locate!

Done now, zzz!

**Comment by s-u** [comment]
Awesome! Taking over :)

**Comment by s-u** [comment]
Ok, I think we're ready to merge now ...

**Comment by gordonwoodhull** [comment]
Go for it and tell QA how to test it!

**Pull request merged**
