### PR TITLE
Shiny 'Aw, shucks' looks nicer

### PR DESCRIPTION
**Pull request by shaneporter**
I was about to open a PR and remembered that the first commit would cause an issue as reported in #1956.

I created a 'special' RCloud shiny SASS file and scoped things within the dialog, so they shouldn't interfere with other Shiny elements.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
The dialog still shows up off to the right when Shiny has already loaded, but it looks good.

Thanks @shaneporter, rebased and merged!

**Comment by shaneporter** [comment]
Sorry it's off to the right in that scenario - is it easy to reproduce?

**Comment by gordonwoodhull** [comment]
Yeah, just kill the server after the shiny page has loaded. 

Another glitch is that we should report a nicer error for the "not published" message, as we do in view.html.

Neither of these really matter, though. Just sort of documenting the glitches here.

**Comment by shaneporter** [comment]
OK, thanks.

**Pull request closed without merging**
