### PR TITLE
Find/replace matches/highlights issues fix

### PR DESCRIPTION
**Pull request by shaneporter**
An alternative approach to updating the search results as the notebook changes was suggested by @gordonwoodhull. Rather than incur an overhead in doing this, only show match highlighting when focus is on the find/replace fields.

As soon as a user clicks on a cell to edit, remove those highlights.

When the user clicks back into a find/replace field, reset the search using the current find/replace text.

This PR implements that functionality, and hopefully closes three bugs: #1839, #1849 and #1960.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
This works great, however it only works when the find dialog loses focus to the cells in particular. 

So for instance you could start typing in the command prompt and generate more cells, or start editing the assets and generate more cells by executing code from there. It also seems more natural to me that the search results would disappear when editing a comment, searching or using help (focus leaving the notebook area).

Do the `focusin` and `focusout` events work on their own without the cell hook?

**Comment by shaneporter** [comment]
I think you're right. There's no need for the specific cell hook. Can use focusout for the dialog. Will confirm in about 12 hours' time. 🙂

**Comment by shaneporter** [comment]
Always good to have fewer lines of (clear) code to do the same things. Please review again @gordonwoodhull. Thanks.

**Comment by gordonwoodhull** [comment]
So this does fix the old issues because it's impossible to save or modify the notebook, or open another notebook, without losing focus. However it creates one new issue #2052, and there is an old but I think unreported bug where it never found unsaved content #2053.

**Comment by gordonwoodhull** [comment]
Rebased and merged. Thanks @shaneporter!

**Comment by shaneporter** [comment]
As I was fixing #2052, I noticed that the 'focus out' approach doesn't catch everything. If you replace the text, the notebook's contents is modified without focus leaving the find/replace form.

**Pull request closed without merging**
