### PR TITLE
Discover fixes

### PR DESCRIPTION
**Pull request by shaneporter**
This should tackle most of the remaining 1.6 Discover issues, except #2030 (I am getting an array of nulls returned for the forks), so the fork count is hard-coded at 1. 

Generally speaking, there are improvements to performance (though I'm not able to verify just how much with a small local instance), UI and browser _bookmarkability_.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Wow, this is huge.

**Comment by gordonwoodhull** [comment]
Oh wow, I love the new look and background!

**Comment by shaneporter** [comment]
Apologies it's so big. I went on a bit of a rampage last night.

In future, it'd be nice to be able to add a description to a notebook, so that it can be picked up here.

**Comment by gordonwoodhull** [comment]
Not a problem at all -  I appreciate a good rampage.

Re: the description, we're actually misusing the description tag as the name of the notebook. (Gists don't have names, github just uses the first filename as the "name".) 

Maybe if we adopt the README cell #1787 (remember that?) we can show an excerpt (title or first paragraph) on the discover page.

**Comment by gordonwoodhull** [comment]
This is just about perfect. I'm going to merge and run with it from here.

**Comment by gordonwoodhull** [comment]
Rebased and merged. Thanks @shaneporter!

**Pull request closed without merging**
