### PR TITLE
Expose Jupyter kernels as RCloud languages 

### LINKED ISSUE #2565: multiple languages in a single extension package
Currently each language extension (`rcloud.r`, `rcloud.python`, ...) implements exactly one language.

Rather than having to create a dummy package for each language supported by Jupyter, why don't we allow each package to return multiple languages when `rcloud.language.support()` is called?

<strike>I think the idiomatic R way of doing this is to return vectors for each field (`language`, `run.cell`, `ace.mode`, etc.) instead of a single value. [setup.R](https://github.com/att/rcloud/blob/e46ab0a4db66779f60390b43ce153a5db08c31b7/rcloud.support/R/setup.R#L355) will have to do more complicated validation/unpacking of the data, but it can be backward compatible. ("Scalar" fields will have the same type, since scalars are length-1 vectors in R; function fields will require a type test, since a vector of function references is different from a function reference.)</strike>

What's really nice about this is that `rcloud.jupyter` can detect at startup time which languages are available, and return that set dynamically.

### PR DESCRIPTION
**Pull request by useless5771**
Jupyter integration is implemented using nbconvert API and its ExecutePreprocessor class which implementation was customised to support code completion, standard input prompts and reuse of kernel instances.

* Introduced RCloudLanguage class representing language support (before simple list was used)
* Exposed Jupyter kernels as languages.
* Exposed configuration of Jupyter kernel mapping to RCloud languages.
* Introduced Jupyter_completer ACE editor component which collects completions produced by Jupyter kernels.
* some minor tweaks/improvements in the way ACE editor Mode instances are created and configured 
* fixed code completions handling produced by vanilla ACE code completers

For details on configuration and available ACE editor modes see REAME.MD file.

This change also fixes worker-(css|html|javascript).js which update was omitted when ACE editor was upgraded to 1.2.6 in RCloud.

FIX #2565

### CODE REVIEW

**Comment by s-u** [comment]
Do you have any docs/examples how to enable this? I tied to install on a clean VM which has Jupyter with kernels installed, but nothing seems to change so I presume there is some configuration?

**Comment by gordonwoodhull** [comment]
@s-u, you read [the README](https://github.com/MangoTheCat/rcloud/blob/ed8dd0d3233cc96d1395af079550d06a55a1dfdc/rcloud.packages/rcloud.jupyter/README.md). I have only skimmed it so far but it looked pretty comprehensive.

**Comment by s-u** [comment]
No, I had no idea that something deep in there describes it :) Does it mean I also have to install `rcloud.jupyter` and add it to the extensions? That's exactly the kind of documentation I was hoping for ...

**Comment by gordonwoodhull** [comment]
Yes, it's a language extension just like the others. The difference is we have updated the spec so that a language extension can support multiple languages, determined automatically.

**Comment by s-u** [comment]
Ok, clean install, minimal RCloud setup, added `rcloud.jupyter` to lang ext and I get

```
Error: session_init: Error in .start.jupyter.adapter(rcloud.session) : 
  could not find function "import"
R trace:
.start.jupyter.adapter(rcloud.session)
rcloud.jupyter.list.kernel.specs(rcloud.session)
d(.session)
withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
suppressWarnings(d(.session))
withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
suppressMessages(suppressWarnings(d(.session)))
start.rcloud.common(...)
start.rcloud.gist(username = username, token = token, ...)
start.rcloud(...)
fun(...)
    at success (http://54.210.175.103:8080/js/rcloud_bundle.js:32:23)
From previous event:
    at Object.session_initAsync (http://54.210.175.103:8080/js/rcloud_bundle.js:38:54)
    at Object.rcloud.session_init (http://54.210.175.103:8080/js/rcloud_bundle.js:451:33)
    at on_connect_anonymous_disallowed (http://54.210.175.103:8080/js/rcloud_bundle.js:4943:24)
    at http://54.210.175.103:8080/js/rcloud_bundle.js:4985:13
From previous event:
    at rclient_promise (http://54.210.175.103:8080/js/rcloud_bundle.js:4982:8)
    at Object.init (http://54.210.175.103:8080/js/rcloud_bundle.js:5037:16)
    at main (http://54.210.175.103:8080/edit.js:16:20)
    at http://54.210.175.103:8080/lib/js/require-common.js:75:17
    at Object.execCb (http://54.210.175.103:8080/lib/js/require.js:1650:33)
    at Module.check (http://54.210.175.103:8080/lib/js/require.js:861:55)
    at Module. (http://54.210.175.103:8080/lib/js/require.js:1113:34)
    at http://54.210.175.103:8080/lib/js/require.js:132:23
    at http://54.210.175.103:8080/lib/js/require.js:1156:21
    at each (http://54.210.175.103:8080/lib/js/require.js:57:31)
    at Module.emit (http://54.210.175.103:8080/lib/js/require.js:1155:17)
    at Module.check (http://54.210.175.103:8080/lib/js/require.js:917:30)
    at Module.enable (http://54.210.175.103:8080/lib/js/require.js:1143:22)
    at Module.init (http://54.210.175.103:8080/lib/js/require.js:774:26)
    at callGetModule (http://54.210.175.103:8080/lib/js/require.js:1170:63)
    at Object.completeLoad (http://54.210.175.103:8080/lib/js/require.js:1564:25)
    at HTMLScriptElement.onScriptLoad (http://54.210.175.103:8080/lib/js/require.js:1671:29)
```

Installed kernels:
```
$ jupyter kernelspec list
Available kernels:
  python2    /usr/local/share/jupyter/kernels/python2
  python3    /usr/local/share/jupyter/kernels/python3
  scala      /usr/local/share/jupyter/kernels/scala
```

Any ideas? It doesn't give much to debug on...

**Comment by s-u** [comment]
Ok, the above is a bug in the `DESCRIPTION` where it list `reticulate` as suggested, but it is actually required. Should probably change it to `Imports` so it gets installed as dependency and used.

**Comment by s-u** [comment]
Please note: if there is an error for a particular language it shouldn't kill RCloud as a whole (which it does now). If unsupported kernels are present they should be handled, e.g., ignored.

**Comment by s-u** [comment]
After removing scala kernel we get:

```
OSError: [Errno 9] Bad file descriptor
```
in the cell output for any code

**Comment by s-u** [comment]
Success! The error goes away after removing `forward.stdio enable` from `Rserve.conf`.

**Comment by s-u** [comment]
Additional note: we are able to run Python2 cell first and then Python3 cell, but not vice versa. After starting Python3 cell first the Pyton2 cell just hangs.

**Comment by useless5771** [comment]
I am looking at the issues that you identified: invalid DESCRIPTION and session crashing if kernel configuration is incorrect.

I am also investigating the python2 startup issue. I can't reproduce this in my dev environment, which is:
* OS: ubuntu1604-desktop
* python 2 version: 2.7.12
* python 3 version: 3.5.2
* ipykernel version in both python2 and python3 is: 4.8.2
* jupyter is installed in python 3 with version: 1.0.0

However I was able to reproduce the issue in our test environment, which is:
* OS: EL7
* python 2 version: 2.7.5
* python 3 version: 3.4.8

(ipython and jupyter versions are the same).

I am investigating this right now.

Can you provide versions of the above installed in your environment, please?

**Comment by s-u** [comment]
- Ubuntu 16.04.2 LTS (AWS EC2 cloud image)
- python 2 version: 2.7.12
- python 3 version: 3.5.2
- ipython2 5.6.0
- ipython3 6.3.1
- jupyter 4.4.0 (via python 3)

Python is system (apt), all python modules are installed via pip (10.0.1)

RCloud is minimal setup, installed via:

```
cd /data
git clone https://github.com/att/rcloud.git
cd rcloud
sudo chown ubuntu /usr/local/lib/R/site-library
sh scripts/bootstrapR.sh

sed -e 's/^#gist/gist/' -e "s/^##Host.*/Host: `curl -s http://urbanek.info/cgi-bin/ip`/" < conf/rcloud.conf.samp > conf/rcloud.conf
echo 'exec.auth: as-local' >> conf/rcloud.conf
mkdir -p data/gists

npm install
sh scripts/build.sh 
sh scripts/fresh_start.sh
```

**Comment by useless5771** [comment]
Thanks, for the record, these are (missing) versions from our environments:
dev:
* ipython2 5.5.0
* ipython3 6.2.1
* jupyter --version: 4.4.0
* pip version 9.0.1 (python3), 9.0.2 (python2)

test env (where I could reproduce the issue):
* ipython2 5.6.0
* ipython3 6.3.1
* jupyter --version: 4.4.0
* pip version 10.0.1

I will upgrade pip on my dev environment, upgrade libraries and try to reproduce the issue.

**Comment by useless5771** [comment]
After upgrading libraries I still wasn't able to reproduce this in my dev environment, well I managed once, but then it disappeared...

However I was able to fix this issue in our test environment. It turned out that for some reason 'python2' kernel was installed twice, but under two different locations. This apparently was causing jupyter to hang when python2 kernel was requested after python3 kernel. Strange... 

Maybe this is a case in your environment, the paths of interest are:

* "/home/<USER_NAME>/.local/share/jupyter/kernels"
* "/usr/local/share/jupyter/kernels"
* "/usr/share/jupyter/kernels"

**Comment by dkey-pugh** [comment]
Executions are confirmed working for Python2, Python 3, Scala, IPerl, JavaScript, Julia, PySpark, SparkR and Spark/Scala. Java execution is not yet tested as it requires Java 9 which is incompatible with other functionality and Go is not currently executing successfully. All the kernals that execute successfully also display functioning code completion with the exception of SparkR and, in addition, Go displays functional code completion.

Plotted outputs have been confirmed for Python2, Python 3, Scala and Julia.

Syntax highlighting is working as expected for all kernels recognised (i.e. all but Java at this stage).

**Comment by gordonwoodhull** [comment]
Thanks @dkey-pugh! Based on this and our own testing and review, I'm "hitting the merge button"!

Please proceed with testing of the fully integrated develop branch. I will also test on my side (and push to our develop server later today).

**Pull request merged**
