### PR TITLE
Feature/print notebook

### PR DESCRIPTION
**Pull request by shaneporter**
I've created an initial print stylesheet, focusing on the cell area (middle column).

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Awesome! This is really close. Couple things I noticed:

 - The welcome message is part of the session, but I don't think folks will want it as part of the printed output. I'm not sure about this, but I'd be inclined to hide it and see if people complain that it's not there, rather than the other way around. It's something they didn't create or ask for.
 - It seems to be over-eager on the page breaks, like it's prioritizing keeping cells or cell output together, rather than minimizing the page count. I think the expected behavior would be to break in the middle of cells, wherever the page runs to.

**Comment by shaneporter** [comment]
Hi @gordonwoodhull - please have a look at my changes, hopefully they address your comments. 
Thanks.

**Comment by gordonwoodhull** [comment]
This addresses #1086

**Comment by gordonwoodhull** [comment]
Looks great! We may still have to do some fine tuning of styles (should it look more like Markdown, with grey code?) and pagination (should cells be kept in one piece in some conditions?) but we can put it out and get feedback on that stuff.

I'm also applying the stylesheet to view.html - I always forget, but generally view.html should be tested whenever edit.html is changed, because they share a lot of code.

**Pull request merged**
