### PR TITLE
Update conf sample

### PR DESCRIPTION
**Pull request by prateek05**
@gordonwoodhull Put in all the config options I had over my head. The list is not comprehensive. There maybe options I haven't used or don't know off

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
seems fine, but why all caps, is it clearer somehow?

**Comment by prateek05** [comment]
Yup

Was working with the spark conf file and everything CAPS makes it more
legible

Moto X@ AT&T

**Comment by s-u** [comment]
errrrr... no :)

**Comment by s-u** [comment]
BTW: you cannot use `##:` because keys have to be unique

**Comment by prateek05** [comment]
:) No to updating ##: again and again. Or the idea of all CAPS ? 
Would it be fine if I rc.cf to ignore all lines starting with '#' ? Can we make '#' as the comment indicator ?

**Pull request closed without merging**
