### PR TITLE
Use configured view to open notebook from recent list

### PR DESCRIPTION
**Pull request by useless5771**
Added a new method resolve_view_link to RCloud.UI.share_button extension which can be used to resolve URLs of view pages for given notebooks.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thanks @useless5771 - could you please refactor a bit so that this code is shared with `set_page`? 

Ideally `resolve_view_link` could take over the version/tag stuff that `set_page` is doing (because next thing you know someone will want to resolve a view link with a version/tag), and then `set_page` could call `resolve_view_link`.

It makes me antsy to have code duplicated like this. I know I'm often guilty of it when I'm in a hurry, but I think we are doing okay for this release so let's get it right.

**Comment by useless5771** [comment]
Thanks, rearranged the code so it is clear what it does and removed code duplication.

**Comment by gordonwoodhull** [comment]
For future reference, the paths to do with version can be tested by going to a historical version of the notebook.

**Comment by gordonwoodhull** [comment]
Thanks @useless5771! The code is much more clear this way. 

The path where there was a version was incomplete, I fixed that in a631a7537f505963. 

Rebased and merged.

**Comment by useless5771** [comment]
Forgot to state that I couldn't test this part, sorry about that. In my dev instance the history of notebooks is most of the time just '...' (if it appears) and clicking on '...' does nothing. I thought this was just temporary regression related to solr and/or filtering feature, but I just updated to the latest 'develop' branch state and I still just get '...' (or nothing).

It appears that there must be something wrong with my instance and I will need to investigate this. @gordonwoodhull , have you experienced similar behavior?

**Comment by gordonwoodhull** [comment]
Ah right that is UI bug #2475. I was able to test only by using the undo key <kbd>ctrl alt z</kbd> to go back a version.

Ain't integration fun?

**Comment by useless5771** [comment]
yep, indeed is fun :) thanks

**Pull request closed without merging**
