### PR TITLE
Fix typo gitgist

### PR DESCRIPTION
**Pull request by prateek05**
@s-u  Hi Simon. Please review contains a fix of misspelled gigistcontext in the gitgist package

### CODE REVIEW

**Comment by s-u** [comment]
Thanks, I have committed a subset of this.

**Comment by prateek05** [comment]
@s-u  the require(github) in login_successful.R is not really required.
https://github.com/prateek05/rcloud/commit/4441c46613cf22308cba5e7fa6bf9d47bae1b84c

**Comment by s-u** [comment]
I bet that's not the only thing not required there ;)

**Comment by prateek05** [comment]
It's slightly annoying to have loading github message on the invoking shell session whenever someone logs in. It traces back to here.

**Comment by s-u** [comment]
But this is only if you don't use github, right? It's still needed if you do (but loaded via gist -> githubgist ...).

**Comment by s-u** [comment]
I'm just a bit wary of unnecessary changes at this point ...

**Comment by prateek05** [comment]
Precisely its loaded via gist->githubgist and isn;t really required even when using github as the backend. 
I am assuming its left over from the era previous to introduction of different backends.
Also agree with second comment. Perhaps after the patch release a rewrite of the code needs to take place.

**Pull request closed without merging**
