### PR TITLE
Updated Smoke test script with search and anonymous user

### PR DESCRIPTION
**Pull request by Prateek032**

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Rebased and merged in 94efb07985f84d8e3a10a919c9f73ffc2fa3260e - 9fb807194a8e6954ce3a481396ff811b27fefdc3

Thanks @Prateek032!

**Comment by gordonwoodhull** [comment]
Hmm, the tests started failing pretty badly with this commit

https://travis-ci.org/att/rcloud/builds/115101215

We'll see if this is just a transient problem or if the tests are broken.

**Comment by Prateek032** [comment]
I think some timing issues in the script, hence tests are failing. I will update the PR by adding  appropriate time in the script

**Comment by gordonwoodhull** [comment]
Thanks @Prateek032!

**Pull request closed without merging**
