### PR TITLE
Right at end/Left at start of ACE widget moves to next/previous cell

### PR DESCRIPTION
**Pull request by shaneporter**
This permits, using right and left cursor keys, the ability to traverse, where appropriate, to the next and previous cell.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thanks @shaneporter. I think the up and down keys would be more intuitive - why the change here?

**Comment by shaneporter** [comment]
Oh right! Yes, at some point in the past I thought of using 'left' and 'right' for this, but yes, you've mentioned 'up' and 'down' keys everywhere. Sorry; I don't know why I became fixated with left/right!

So, it's just a case of swapping 'left' for 'up', and 'right' for 'down'? I can do that.

**Comment by gordonwoodhull** [comment]
Cool! I think it's a tiny bit simpler because you only have to check line and not column.

**Comment by shaneporter** [comment]
Yeah, you're right. I'll make the change. Good to be simpler.

**Comment by shaneporter** [comment]
So, the rules should be:

- Go to previous cell: if there is a previous cell and __up__ arrow is pressed and you're on the first line
- Go to next cell: if there is a next cell and __down__ arrow is pressed and you're on the last line.

**Comment by shaneporter** [comment]
So, I was going to remove the left/right handling, but I think it compliments the (albeit more intuitive) up/down handling.

Try it - I think the left/right should stay, but happy to remove the left/right if you have strong objections.

**Comment by gordonwoodhull** [comment]
You know me, I like having lots of ways of doing things. The left/right is awesome too.

Arguably up/down should go to the same character instead of the beginning (or end of line if shorter) but we can think about that later.

Rebased and merged. Thanks @shaneporter!

**Comment by shaneporter** [comment]
Good point about up/down.

**Pull request closed without merging**
