### PR TITLE
Next/previous search result hopping

### PR DESCRIPTION
**Pull request by shaneporter**
Should implement the required functionality for #2192.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
This is a good start. But the command isn't enabled when a cell is active. 

I'd also expect some attempt to continue either from where the last find let off, or from where the cursor or cell selection is, when the find dialog has lost focus. But maybe we should put that part off.

**Comment by gordonwoodhull** [comment]
This is actually a really complex little feature, so maybe we should put it off. Search "again" isn't quite as useful if it starts over from the beginning each time it's invoked.

**Comment by shaneporter** [comment]
Hi @gordonwoodhull - please could you take a look at this when you have a moment.

**Comment by gordonwoodhull** [comment]
I don't see the keys mapped for cells, so it's hard to test this. (Was there a file left out of the commits?) The code looks good otherwise.

Also, it doesn't set focus to the find "dialog" if it's already open, so nothing happens in that case.

**Comment by shaneporter** [comment]
Whilst looking at this, I found that initiating a search with 'shift-f3' or 'ctrl-shift-g' goes to the first match, rather than the looking back from the cursor.

**Comment by gordonwoodhull** [comment]
Right, I can invoke the command only outside of the cells (as a global hotkey), not from within a cell where it's most useful. So the ace hotkeys need to be modified for cells.

I was figuring this was the reason it was going to the first match rather than continuing from the current cursor position: because there is no current cursor position.

**Comment by gordonwoodhull** [comment]
Looks like what happens is that Ace already has a different find next and find previous, which we don't want. (It looks for the currently *selected* text.)

But it's bound to different keys on Mac and Windows, so it's letting you take the key on Windows:

```js
JSON.stringify(widget.commands.commands.findnext, null, 2)
{
  "name": "findnext",
  "bindKey": {
    "win": "Ctrl-K",
    "mac": "Command-G"
  },
  "readOnly": true
}
```

Adding the following lines to the cell view's `create_edit_widget()` fixes it (in 56de411bf87):
```js
        ace_widget_.commands.removeCommand('findnext');
        ace_widget_.commands.removeCommand('findprevious');
```

**Comment by gordonwoodhull** [comment]
Works great!

Thanks @shaneporter! Rebased and merged.

**Comment by shaneporter** [comment]
Thanks for the explanation @gordonwoodhull!

**Pull request closed without merging**
