### PR TITLE
Replace fields hidden for read-only notebooks

### PR DESCRIPTION
**Pull request by shaneporter**
I considered there to be two issues with #1958. The first was that the 'replace' fields could be shown for read-only notebooks using the keyboard shortcut. That was implemented with the fix for #1876 (submitted with PR #1965).

The second issue is that the 'replace' fields are not hidden when (using undo) the notebook changes from writable to read-only. Commit 5fe27bd fixes this with two straightforward modifications, described in the changed files below.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
This borks if you load a readonly notebook without having previously opened the find/replace dialog. (E.g. if the current notebook/version is readonly and the page is reloaded.)

**Comment by shaneporter** [comment]
I'll take a look at that!

**Comment by shaneporter** [comment]
Able to reproduce, and hopefully fixed with that last commit.

**Comment by gordonwoodhull** [comment]
Thanks @shaneporter it's all happy now.

Rebased and merged.

**Pull request closed without merging**
