### PR TITLE
Solr calls with exception handling

### LINKED ISSUE #2318: Handle SOLR connection issues gracefully
At times when SOLR Calls land in
1) Unable to reach host
2) Unable to resolve DNS name
3) Unable to get a response
4) Request Timeouts

The error should be passed to ulog and warnings formatted and passed to the session pane ?

### PR DESCRIPTION
**Pull request by prateek05**
fixes #2318

### CODE REVIEW

**Comment by prateek05** [comment]
There is still one issue remaining. In instances with cross instance search if any of the nodes gets into an error. The result set errors out with the exceptions from the parsing code. The parsing code is way too difficult to introduce any sanity checks :(

**Comment by prateek05** [comment]
@gordonwoodhull Review

**Comment by gordonwoodhull** [comment]
I took a quick look but I'm gonna have to take your word on this, as I've never worked with the login code. I'll merge tomorrow unless @s-u objects.

**Comment by prateek05** [comment]
@gordonwoodhull No this one is with the exceptions in solr calls. Login code is resolved.

**Comment by gordonwoodhull** [comment]
Confirmed it fixes the issue on chusuk. Merging.

**Pull request closed without merging**
