### PR TITLE
Enhancement/select cell improvements

### PR DESCRIPTION
**Pull request by shaneporter**
Proposed fixes for:

- #1834 (though this does behave like Gmail, and does not disable)
- #1827 
- #1826 
- #1825

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
This is very close. However there are still a few quirks:

Re #1834 no cells:
 - There should be a visual indication that the checkbox and the menu items are disabled, i.e. they should be greyed out. (I notice gmail doesn't do this, but Google isn't particularly known for its UI expertise.)

Re #1826:
 - Although unmodified click now correctly selects just one, ctrl/cmd-click should still toggle the selection when clicking the title/bar. This is consistent with file browsers. This is one of those places where we have to special case OSX and separate ctrl- and cmd-, because ctrl-click means right click on OSX.
 - There's now a bug with clicking a checkbox where it selects properly but the checkbox itself can get out of sync (the cell is selected but the checkbox is not, or vice versa). Perhaps the event is being handled twice, once for the bar and once for the checkbox?

**Comment by shaneporter** [comment]
@gordonwoodhull another update; can't check the first point regarding #1826, since I don't have a mac, but hopefully it will now work as expected.

**Comment by gordonwoodhull** [comment]
Looks like everything is fixed but single selection doesn't work anymore. So I can toggle but the behavior where clicking on the title/bar of an individual cell does not select that and deselect everything else.

I think I'll go ahead and merge this and open a new issue, since this is a lot better.

**Comment by gordonwoodhull** [comment]
merged

**Pull request closed without merging**
