### PR TITLE
incremental search doesn't throw an error in mini

### PR DESCRIPTION
**Pull request by shaneporter**

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Thanks @shaneporter.

It also crashes in view.html, so could you please refine this fix a little further?

RCloud is definitely too tightly bundled together: I don't remember if there is a way to initialize something that is just for edit mode, and there are an awful lot of things in `RCloud.UI.init' that are only for edit mode.

```
TypeError: text is undefined[Learn More]  underscore.js:1236:5
	_.template http://minimonolith.dev.local:8080/lib/js/underscore.js:1236:5
	init incremental_search.js:24:25
	RCloud.UI.init init.js:70:4
	main http://minimonolith.dev.local:8080/view.js:15:5
	start_require/< http://minimonolith.dev.local:8080/lib/js/require-common.js:75:17
	execCb http://minimonolith.dev.local:8080/lib/js/require.js:1650:24
	check http://minimonolith.dev.local:8080/lib/js/require.js:861:47
	enable/</< http://minimonolith.dev.local:8080/lib/js/require.js:1113:29
	bind/< http://minimonolith.dev.local:8080/lib/js/require.js:132:20
	emit/< http://minimonolith.dev.local:8080/lib/js/require.js:1156:21
	each http://minimonolith.dev.local:8080/lib/js/require.js:57:31
	emit http://minimonolith.dev.local:8080/lib/js/require.js:1155:17
	check http://minimonolith.dev.local:8080/lib/js/require.js:917:25
	enable http://minimonolith.dev.local:8080/lib/js/require.js:1143:17
	init http://minimonolith.dev.local:8080/lib/js/require.js:774:21
	callGetModule http://minimonolith.dev.local:8080/lib/js/require.js:1170:17
	completeLoad http://minimonolith.dev.local:8080/lib/js/require.js:1564:25
	onScriptLoad
```

**Comment by shaneporter** [comment]
Oh sorry for not spotting that @gordonwoodhull. I'll take a look.

**Comment by gordonwoodhull** [comment]
I've gotten past this error along with the other fix included in #2485. I'm getting a different error in view mode which I'll post separately, since it's back to problems in editor_tab - incremental_search seems to be okay.

**Comment by gordonwoodhull** [comment]
Rebased and merged. Thanks @shaneporter!

**Pull request closed without merging**
