### PR TITLE
Asset and Group names are trimmed prior to name check

### PR DESCRIPTION
**Pull request by shaneporter**
`trim()` to the rescue.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
We'll need this in at least two more places: Group Rename, and Asset Rename. I'll just leave this open so you don't have the overhead of opening another PR.

**Comment by shaneporter** [comment]
dd48788 should fix the group rename.

I started looking at asset rename and found another issue. If you perform a rename with the _same_ name, it complains that an asset of that name already exists.

**Comment by shaneporter** [comment]
Hi @gordonwoodhull - e7aa133 now checks if the user has changed the asset name before checking if it exists. Please re-review this PR. Thanks.

**Comment by gordonwoodhull** [comment]
Rebased and merged. Thanks @shaneporter!

**Pull request closed without merging**
