### PR TITLE
Use grunt instead of make

### PR DESCRIPTION
**Pull request by gordonwoodhull**
and generate source maps

@s-u, I think we discussed using npm's grunt tools instead of make, mostly so that we can have source maps and don't have to search through rcloud_bundle.js all the time. 

as described in #1789, it will also help us clean up the CSS with SASS, and lint the JS.

does this look okay to you? if you take a look at the artifacts commit you can see that the result is exactly the same except for some line breaks.

it just means you have to `npm install` at root instead of in those two directories. build.sh is a little bit slower, too, but not significantly.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
@s-u, are you okay with this one? It will help front-end debugging a lot.

**Comment by s-u** [comment]
Yep, thanks, good with me.

**Comment by s-u** [comment]
Actually, the `build.sh` doesn't seem right:

```
$ sh scripts/build.sh 
scripts/build.sh: line 47: grunt: command not found
``

Obviously, there is no `grunt` command (it's a module not a system binary) so that probably needs fixing ...

**Comment by gordonwoodhull** [comment]
Hmm, good point. 

We require `npm` to be installed and this would assume that you also installed grunt globally using `npm install -g grunt-cli `

But we can eliminate that step and run `node_modules/grunt-cli/bin/grunt` instead, I think. Will change & test this before I merge.

**Comment by s-u** [comment]
After some googling it seems that it also requires `grunt-cli` so you have to add that to `package.json` and then

```
diff --git a/scripts/build.sh b/scripts/build.sh
index b24e32c..f4021d6 100755
--- a/scripts/build.sh
+++ b/scripts/build.sh
@@ -44,7 +44,7 @@ fi
 
 # build JS (if available)
 if [ -d ./node_modules ]; then
-    grunt
+    node_modules/grunt-cli/bin/grunt
 fi
 
 # check if we need to worry about mathjax
```

**Comment by gordonwoodhull** [comment]
Merged!

**Pull request closed without merging**
