### PR TITLE
Selected word should populate the find replace 'find' field; tab order on Find/Replace 'dialog'

### PR DESCRIPTION
**Pull request by shaneporter**
An implementation for #1846.

Fixes for #1984 and #1986, both of which are related.

I also include a commit ba563b8, which includes the find/replace close dialog's close button. Seems sensible to me, but easy to leave out if it's not wanted.

### CODE REVIEW

**Comment by shaneporter** [comment]
Hi @gordonwoodhull - please can you review this PR? Commit dc33d0f should hopefully tackle the document selection issue.

**Comment by gordonwoodhull** [comment]
@shaneporter, this does work but of course I would prefer to reuse the code as a shared function rather than copying and pasting all that hackiness. I guess it belongs in ui_utils.js.

**Comment by shaneporter** [comment]
Agreed. I'll make it better.

**Comment by gordonwoodhull** [comment]
Actually, I'm closing this PR because I already merged all but the last commit, and forgot to close it. (It's easy for me to cherry pick individual commits but I might forget.)

**Comment by gordonwoodhull** [comment]
For future reference, the re-opened document selection issue is still #1846

**Pull request closed without merging**
