### PR TITLE
Add resolution of _htmlwidgets urls for users packages

### PR DESCRIPTION
**Pull request by useless5771**
this fixes att/rcloud.htmlwidgets#6

The problem here was that the additional '_htmlwidgets' urls were just supported for packages installed globally in rcloud. When user tried to use a package that got installed into their library directory, the '_htmlwidgets' urls were not resolved.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Fantastic! Five fixes!

I know it's extra work, and it doesn't matter much for small fixes like these, but in the future, please open a branch and a new PR for each fix. 

It's easier for me to review, and in case I need to selectively merge some fixes but not others, I won't leave some commits dangling that way.

**Comment by useless5771** [comment]
Yes, I noticed that. I will raise pull requests from feature branches from now on.

**Comment by useless5771** [comment]
@gordonwoodhull  please could you review this PR and merge the commits if they are fine?

(I have three bug-fix branches for which I would like to raise PRs but they are based on changesets in this pull request, so when I try to raise new pull request github includes these not-yet-merged changes in them as well.)

Thanks

**Comment by gordonwoodhull** [comment]
Yes! I do apologize for the delay. Today is 90% RCloud for me, so I should have this merged by EOD if not sooner.

**Comment by gordonwoodhull** [comment]
Ah, one more procedural request (sorry). Usually when submitting a PR, it's customary not to include the generated artifacts (in this case `*_bundle.*`), since those just add noise to the commits and make the merges slightly more difficult.

I wish we didn't have these checked in at all (#1728), but until we solve the tooling/distribution problem, please omit these from your commits. This is a best practice for most open source projects. 

Thanks!

**Comment by useless5771** [comment]
Yes, I was surprised that these are not ignored, just assumed that since https://github.com/att/rcloud/blob/develop/doc/INSTALL.md suggests that node.js and npm, are somewhat optional then these are expected to be committed... (as minified and source get out of sync)

Ok, I will exclude these from my commits then.

**Comment by gordonwoodhull** [comment]
Thanks... Yes, we're in a bit of a rut where we need them committed for every release, because we want people to be able to run RCloud without Node tools, but we don't want to commit them when we're between releases because it's a mess.

Once we develop a process for pushing built releases to GitHub, we can finally stop checking this junk in.

**Comment by gordonwoodhull** [comment]
Hi @useless5771 - I was not able to verify the first fix on this branch, but the others look great, so I've merged everything except 355cba6.

The fix for #2371 is not guaranteed to work because the default action for the link opening a new tab runs in parallel with the save. But I appreciate that you did it this way because it's better than using javascript to follow a link. In practice this should be fine and of course it tests well. 

(I only noticed this because I'm paranoid about dropping promises after many bad experiences.)

I'll return to the original fix for `shared.R` when I can figure out how to repro multiple-user installs in a test environment. Hopefully merging the rest is enough to get you unstuck on your other PRs.

**Comment by gordonwoodhull** [comment]
I put the single remaining commit on #2407

**Comment by useless5771** [comment]
Thanks @gordonwoodhull , I sorted out the mess with our fork history and raised four pull requests based on current rcloud head so it should be quick to review/merge these.

**Pull request closed without merging**
