### PR TITLE
Feature/notebook protection api

### PR DESCRIPTION
**Pull request by gordonwoodhull**
@s-u, please review my R, and that this implements the API we've discussed. I've done basic testing at the command line, but this is the kind of stuff that would unit test really well (with `rcloud.support:::configure.rcloud("script")`) - is there a good way to do that?

@anatoliyg, please also review this is what you expect. I think this is complete, but as an optimization we might add a wrapper API that takes multiple group modifications at once.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Here is the RCS schema. Not sure if some of this will get replaced with cryptographic techniques?

Domain: `.cryptgroup`

`.cryptgroup/<groupid>/name` - group name
`.cryptgroup/<groupid>/users/<user>` - is.admin

`<user>/system/cryptgroups/<groupid>` - is.admin

Notebooks:
`.notebook/<notebook-id>/cryptgroup` - groupid

Basically, the existence of a key indicates whether a user belongs to a group, or a user has a group. If the value is TRUE, the user is an admin, otherwise they are just a member.

**Comment by anatoliyg** [comment]
hey Gordon, is "notebook.protection.R" the file that's containing the API
I'm accessing from front end? new to R.

--
A

On Wed, May 27, 2015 at 9:52 AM, Gordon Woodhull <notifications@github.com>
wrote:

> Here is the RCS schema. Not sure if some of this will get replaced with
> cryptographic techniques?
>
> Domain: .cryptgroup
>
> .cryptgroup/<groupid>/name - group name
> .cryptgroup/<groupid>/users/<user> - is.admin
>
> <user>/system/cryptgroups/<groupid> - is.admin
>
> Notebooks:
> .notebook/<notebook-id>/cryptgroup - groupid
>
> Basically, the existence of a key indicates whether a user belongs to a
> group, or a user has a group. If the value is TRUE, the user is an admin,
> otherwise they are just a member.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/att/rcloud/pull/1464#issuecomment-105919209>.
>



-- 
Anatoliy

**Comment by gordonwoodhull** [comment]
Yeah, we still need the JS bindings, which is mostly annoying mechanical work. I can do that right now.

**Comment by gordonwoodhull** [comment]
rcloud.js exists mostly so that we can set breakpoints on the stubs, otherwise it is just promisifying the asynchronous methods that it gets from rserve.js

**Comment by gordonwoodhull** [comment]
okay, the js part is untested, so if there are any obvious errors, my apologies

**Comment by gordonwoodhull** [comment]
oops, and R ocap wrappers..

**Pull request closed without merging**
