### PR TITLE
fix #1387 - adding HTML highlighting of assets

### LINKED ISSUE #1387: HTML highlighting
in asset pane

### PR DESCRIPTION
**Pull request by anatoliyg**

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
For the "define is not defined" error, it looks like we need to use the built version of ace, not the sources. 

http://stackoverflow.com/questions/10883190/ace-editor-define-is-not-defined

I think this may be the step I forgot about. I have been building ace and then copying files from one of the subdirectories. I'd have to check my other computer to remember which one, but the question points to a built version which should work for this single file.

**Comment by anatoliyg** [comment]
Ok , got it. Thanks , Gordon

**Comment by gordonwoodhull** [comment]
Thanks, went ahead and built ace so I could remember how to do it, copied in the html worker (lots bigger with all the dependencies), and merged.

**Comment by anatoliyg** [comment]
Thanks. I had the right version of the worker locally, forgot to check it in

**Pull request merged**
