### PR TITLE
2151 remove binary assets from search index

### LINKED ISSUE #2167: Dont index binary assets in the search index
Refer discussion #2151

### PR DESCRIPTION
**Pull request by prateek05**
Closes #2167

### CODE REVIEW

**Comment by prateek05** [comment]
@gordonwoodhull This should work.

**Comment by gordonwoodhull** [comment]
Thanks @prateek05! Looks good.

**Comment by gordonwoodhull** [comment]
I noticed one other small issue. 

The original call to `update.solr` did the check to see if SOLR is enabled outside the call. The new calls don't do this, so they are failing on non-search-enabled setups. Any objections to just exiting the function if SOLR is not enabled? I can make the change if this is OK.

**Comment by prateek05** [comment]
The line from the original does exist. 
https://github.com/att/rcloud/blob/release/1.6/rcloud.support/R/search.R#L37 
Let me check

**Comment by gordonwoodhull** [comment]
Yeah, but it's failing hard with `stop` rather than just returning. I think it should be okay to just skip it but I'm wary of messing with this code.

**Comment by prateek05** [comment]
I think i traced it down to the deletion of notebook. Ideally the check should be moved to `.solr.post` to safeguard. Let me put a check there that should safeguard from all higher level calls

**Comment by gordonwoodhull** [comment]
I noticed it on creating a notebook - `rcloud.set.notebook.visibility` calls `update.solr` which stopped.

**Comment by prateek05** [comment]
Right and also `.solr.delete.doc`. 
ba5b4df the condition check is in the lower `.solr.post` that way its safeguarding any solr related functions to skip the process if the config does not have an entry for solr url

**Comment by gordonwoodhull** [comment]
Great, rebased and merged (minor changes). Thanks @prateek05!

**Pull request closed without merging**
