### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by prateek05**
Initial draft more changes to come

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Is this worth putting in the release? I haven't cut the tag yet.

I guess it is fairly independent so maybe it doesn't matter.

**Comment by prateek05** [comment]
We could add it. It's completely independent.

**Comment by prateek05** [comment]
Let's hold on to this. I have to add python iotools and others. We can merge it in the master later on ?

**Comment by gordonwoodhull** [comment]
Okay let's target it for "1.6.1" which is features that didn't make it into 1.6 (but will turn into 1.6.2 if we do a patch release).

**Comment by prateek05** [comment]
Hi @gordonwoodhull 
This is good to be merged for the first standalone container

develop and 1.6.1 ?

**Comment by gordonwoodhull** [comment]
Great, thanks @prateek05!

**Pull request merged**
