### PR TITLE
Htmlwidgets

### PR DESCRIPTION
**Pull request by gaborcsardi**
Sizing in mini.html is not right yet, I'll fix that later.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
@gaborcsardi, this is fantastic! I am sure there will be glitches along the way, but it works so well, it's almost as if htmlwidgets were designed with RCloud in mind. (In fact, I think @ramnathv put some effort getting rCharts to work in RCloud back in the day, so perhaps that experience informed htmlwidgets somewhat.)

So far I haven't observed the iframes and most of the htmlwidgets packages work. The ones that don't either seem to be slightly ill-behaved or perhaps their examples are incomplete. I'll open issues for those individually.

One thought I had is that the code is so self-contained that we might put it into its own package. However, this would just be for organization's sake; I think we will always want to load the package by default.

We will also want to get rid of the iframes someday but that's not a priority and it's going to be tough integrating htmltools dependency tracking with our requireJS-based dependencies.

**Comment by gordonwoodhull** [comment]
Rebased and merged. Thanks @gaborcsardi!!

Working examples in this gist/notebook: 
https://gist.github.com/gordonwoodhull/5f0efc1a3c5b6b1d0d6a122955f4d271

Not-working examples in this notebook (DiagrammeR and one of the formattable examples):
https://gist.github.com/gordonwoodhull/1fa87bea8a5dd7aa025075fe5e905abb

**Comment by gordonwoodhull** [comment]
Hard to put this down but I have to get to my other merges and last-minute features. 

I'll try the rest of the [htmlwidgets gallery](http://gallery.htmlwidgets.org/) this week.

**Comment by gordonwoodhull** [comment]
I also have not tested with mini.html yet.

**Comment by gaborcsardi** [comment]
Thanks! Don't try mini.html yet, the widgets show up, but sizing does not
work there. I need some more time to work that out properly, but I'll get
to it this week.

**Comment by gaborcsardi** [comment]
OK, sizing is better now, and it also works properly in mini.html. It is in https://github.com/MangoTheCat/rcloud/tree/htmlwidgets-mini

I'll submit a PR later today, I still want to add some docs on how it works, as it is quite tricky to get all the cases "right", and if I don't write this down now, it will be a nightmare to decipher it later....

FYI.

**Comment by gordonwoodhull** [comment]
Hi @gaborcsardi, we're starting beta testing this weekend on the research instance and on rcloud.social. Are your fixes ready?

Overall we found that htmlwidgets work very well. I did notice that rbokeh usually had too small a window so hopefully your changes address that. Cheers!

**Comment by gaborcsardi** [comment]
OK. PR submitted. Sorry for the delay. I added docs on how the resizing and the widgets in general work:
https://github.com/att/rcloud/pull/2133/commits/a79f0561b9608bb51da5168399c0b2b0f74a5f55
Please ask if sg is not clear, or tell me if sg can be or has to be changed or improved.

I don't think this'll fix rbokeh, but there is a slight chance.

**Comment by gaborcsardi** [comment]
PR is #2133, just to have the cross links.

**Pull request closed without merging**
