### PR TITLE
Secured SOLR with HTTP Basic Auth

### PR DESCRIPTION
**Pull request by prateek05**
Based on Solr 5 release. Basic Authentication is a part of the setup for organization to apply ACL

Introducing two new configuration parameters. 
solr.auth.user
solr.auth.pwd

The commit has been tested on my side with the three scenarios
1) Parent Solr with Basic Auth and remote SOLR with unsecured SOLR
2) Parent Solr unsecured and remote SOLR with Basic Auth
3) Unsecured Solr as parent and remote

Modules tested:
1) Comments (modify/delete/create)
2) Search (update/search notebooks)

### CODE REVIEW

**Comment by prateek05** [comment]
Hi @s-u 
Can you review this PR when time permits
Hint: you can add ?w=1 to the GitHub diff url to ignore whitespace.

**Comment by gordonwoodhull** [comment]
Ping @s-u - hoping to give QA a week to test before March 1.

**Comment by gordonwoodhull** [comment]
merged to hotfix/1.5.2

**Comment by gordonwoodhull** [comment]
@prateek05, @s-u, I've also moved all the search functions to search.R in 6be31f9be7e175f12a1b6e916bd0d2a559b54fe3

Please verify.

**Pull request closed without merging**
