### PR TITLE
Feature/document shortcuts

### PR DESCRIPTION
**Pull request by shaneporter**
Initial changes for documenting shortcuts. Try '?' to see the shortcuts dialog.

Points of interest:

- the shortcuts are managed using [Mousetrap](https://craig.is/killing/mice)
- `shortcut_manager` uses the extension API. Not sure if it's using it in the intended way, but I welcome comments.
- shortcuts are added using the following code:

```
 RCloud.UI.shortcut_manager.add([{
        category: 'General',
        id: 'show_help',
        description: 'Show shortcuts help',
        keys: [
            ['?']
        ],
        action: function() { RCloud.UI.shortcut_dialog.show(); } 
    }]);
```

the `keys` property is an array of arrays; let's have a look at another example:

```
 keys: [
    ['ctrl', 'k'],
    ['command', 'k']
 ],
```

This contains options for non-mac and mac. The shortcut manager filters out mac commands for non-mac systems using the `ui_utils.is_a_mac' function. 

On my PC, I don't see the 'command k' option.

- Prior to registering, shortcuts are checked to see if they clash. If so, they are not registered, and a warning message output to the console.
- The category property, which defaults to 'General' if not supplied, is used to dynamically construct the shortcuts dialog's headings.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Excellent. Good thought to use a library for key bindings. I look forward to reviewing this! 

(Unfortunately I'm out with the flu, so that may not be until later this week.)

**Comment by shaneporter** [comment]
Sorry to hear you're not feeling well. I've just done the cell select related enhancements and submitted a pull request for those.

What would you like me to focus on next? I'm thinking of taking a look at the Notebook recommendations. I don't have anything against AngularJS, but it seems a little overkill for what's currently there. I could definitely trim things down a lot.

**Comment by gordonwoodhull** [comment]
Yes, cleaning up the recommendation code sounds like a good idea.

If you're up for a bigger challenge, we have a cluster of related requests around sorting the notebook tree - #522 #1075 and some other linked issues. This code (in editor_tab.js don't ask) is the oldest and badly needs a refactor. It's not on our list for this release but we have to attack it sometime. 

It's also the source of our biggest performance bottleneck, which is in this release, but solving that may require some server side work as well.

**Comment by gordonwoodhull** [comment]
The perf problems are #405 #1780 #1781 - even if you don't take this on, another pair of eyes will help.

**Comment by shaneporter** [comment]
I have pushed a fix for issue #1847 with this pull request (since it overhauls the shortcuts management.)

**Comment by gordonwoodhull** [comment]
This looks great. My only suggestion is that it only display the shortcut keys for the current platform, since no one is going to care about other platforms and it just clutters it up. I'll open a separate issue for that.

Now we just have to add a bazillion other shortcut keys!

**Pull request merged**
