### PR TITLE
Added 'show keyboard shortcuts' to help pane.

### PR DESCRIPTION
**Pull request by shaneporter**
Not sure if you'll like the keyboard (`<i class="icon-keyboard"></i>`) in the link, but I won't be offended if you remove it.

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
heheh, cute.

**Comment by gordonwoodhull** [comment]
This is great. Only change I'd like to see is that, since vertical real estate is precious, this should fit to the right of the search form. I tried to fix it myself and got bogged down in CSS/HTML, so I'm going to pass this back to you. 

We can trim the text down to just "keyboard shortcuts" or even "keyboard", if it won't fit otherwise.

**Comment by shaneporter** [comment]
I changed the link text to 'Keyboard', but kept the little keyboard icon.

At a smaller window size, it is possible to overlap the link with the help input/button, but I don't know how many users will encounter this issue during normal use.

Please re-review @gordonwoodhull. Thanks. :smile:

**Comment by gordonwoodhull** [comment]
Rebased and merged. Thanks @shaneporter!

**Pull request closed without merging**
